CREATE TABLE `invoice_info` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `OPTIMISTIC` bigint(20) NOT NULL DEFAULT 0 COMMENT '乐观锁',

  `INVOICE_NO` varchar(32) NOT NULL COMMENT '发票号码',
  `INVOICE_CODE` varchar(32) NOT NULL COMMENT '发票编号',

  `BUYER_NAME` varchar(1024) NULL DEFAULT NULL COMMENT '购买方名称',
  `BUYER_TAX_NUM` varchar(1024) NULL DEFAULT NULL COMMENT '购买方-纳税人识别号',
  `BUYER_ACCOUNT` varchar(1024) NULL DEFAULT NULL COMMENT '购买方-开户行\账号',
  `BUYER_CONTACT` varchar(1024) NULL DEFAULT NULL COMMENT '购买方-地址\电话',

  `SALER_NAME` varchar(1024) NULL DEFAULT NULL COMMENT '销售方名称',
  `SALER_TAX_NUM` varchar(1024) NULL DEFAULT NULL COMMENT '销售方-纳税人识别号',
  `SALER_ACCOUNT` varchar(1024) NULL DEFAULT NULL COMMENT '销售方-开户行\账号',
  `SALER_CONTACT` varchar(1024) NULL DEFAULT NULL COMMENT '销售方-地址\电话',

  `INVOICE_DATE` varchar(32) NOT NULL COMMENT '开票日期',
  `NO_TAX_AMOUNT` DECIMAL(10,2) NOT NULL COMMENT '不含税合计',
  `TAX_AMOUNT` DECIMAL(10,2) NOT NULL COMMENT '税额',
  `TOTAL_TAX_AMOUNT` DECIMAL(10,2) NOT NULL COMMENT '价税合计',
  `INVOICE_COMMENT` varchar(2048) NULL DEFAULT NULL COMMENT '发票备注',
  `PROVINCE` varchar(32) NULL DEFAULT NULL COMMENT '省份',
  `INVOICE_TYPE` varchar(32) NULL DEFAULT NULL COMMENT '发票类别',
  `MACHINE_CODE` varchar(32) NULL DEFAULT NULL COMMENT '开票机编码',

  `STATUS` varchar(32) NULL DEFAULT NULL COMMENT '数据状态',
  `DESCRIPTION` varchar(2048) NULL DEFAULT NULL COMMENT '描述',
  `CREATE_USER` varchar(32) NULL DEFAULT NULL COMMENT '创建人',
  `CREATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATE_USER` varchar(32) NULL DEFAULT NULL COMMENT '修改人',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `INVOICE`(`INVOICE_NO`, `INVOICE_CODE`)
) COMMENT = '发票信息表';

CREATE TABLE `invoice_detail` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `OPTIMISTIC` bigint(20) NOT NULL DEFAULT 0 COMMENT '乐观锁',

  `INVOICE_NO` varchar(32) NOT NULL COMMENT '发票号码',
  `INVOICE_CODE` varchar(32) NOT NULL COMMENT '发票编号',

  `GOODS_NAME` varchar(2048) NULL DEFAULT NULL COMMENT '货物或应税劳务/服务名称',
  `SPECIFICATIONS` varchar(2048) NULL DEFAULT NULL COMMENT '规格',
  `UNITS` varchar(64) NULL DEFAULT NULL COMMENT '单位',
  `GOODS_SUM` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '数量',

  `GOODS_PRICE` DECIMAL(10,2) NOT NULL COMMENT '单价',
  `NO_TAX_AMOUNT` DECIMAL(10,2) NOT NULL COMMENT '不含税合计',
  `TAX_RATE` DECIMAL(10,2) NOT NULL COMMENT '税率',
  `TAX_AMOUNT` DECIMAL(10,2) NOT NULL COMMENT '税额',

  `ORDERS` int(11) NULL DEFAULT NULL COMMENT '排序值',
  `STATUS` varchar(32) NULL DEFAULT NULL COMMENT '数据状态',
  `DESCRIPTION` varchar(2048) NULL DEFAULT NULL COMMENT '描述',
  `CREATE_USER` varchar(32) NULL DEFAULT NULL COMMENT '创建人',
  `CREATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATE_USER` varchar(32) NULL DEFAULT NULL COMMENT '修改人',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  INDEX `INVOICE`(`INVOICE_NO`, `INVOICE_CODE`)
) COMMENT = '发票明细表';

CREATE TABLE `invoice_request` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `OPTIMISTIC` bigint(20) NOT NULL DEFAULT 0 COMMENT '乐观锁',

  `INVOICE_NO` varchar(32) NOT NULL COMMENT '发票号码',
  `INVOICE_CODE` varchar(32) NOT NULL COMMENT '发票编号',
  `INVOICE_DATE` varchar(32) NOT NULL COMMENT '开票日期',
  `NO_TAX_AMOUNT` DECIMAL(10,2) NOT NULL COMMENT '不含税合计',

  `REQUEST_RESULT` varchar(32) NULL DEFAULT NULL COMMENT '请求结果',
  `COMMENT` blob NULL DEFAULT NULL COMMENT '内容',

  `ORDERS` int(11) NULL DEFAULT NULL COMMENT '排序值',
  `STATUS` varchar(32) NULL DEFAULT NULL COMMENT '数据状态',
  `DESCRIPTION` varchar(2048) NULL DEFAULT NULL COMMENT '描述',
  `CREATE_USER` varchar(32) NULL DEFAULT NULL COMMENT '创建人',
  `CREATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATE_USER` varchar(32) NULL DEFAULT NULL COMMENT '修改人',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `INVOICE`(`INVOICE_NO`, `INVOICE_CODE`, `INVOICE_DATE`, `NO_TAX_AMOUNT`)
) COMMENT = '发票请求表';