spring:
  cloud:
    sentinel:
      eager: true
      transport:
        dashboard: 127.0.0.1:5551
      datasource:
        file:
          file: 'classpath: flowrule.json'
          data-type: json