server:
  port: 10001

info:
  name: @project.artifactId@
  version: @project.version@
  description: @project.description@

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# spring config
spring:
  application:
    name: @project.artifactId@
  jmx:
    default-domain: @project.artifactId@
  # session 使用 redis 管理
  session:
    store-type: redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true
  # redis
  # redis单一模式
  redis:
    host: 127.0.0.1
    port: 6379

    # redis哨兵模式
    #    sentinel:
    ## Redis服务器master的名字
    #      master: mymaster
    ## redis-sentinel的配置地址和端口
    #      nodes:
    #################redis基础配置#################
    # 密码
    password:
    # 库
    database: 1
    # 超时时间
    timeout: 60S
    # redis线程池设置
    pool:
      jedis:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 500
        #连接池中的最小空闲连接，默认值也是0。
        min-idle: 50
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
        max-active: 100
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 1000

    # 超时配置（秒）
    expir:
      # 默认24小时(24 * 60 * 60)
      default-config: 86400
      config:
        test22: 80
        test1: 60

  # sharding-jdbc分库分表的配置
  shardingsphere:
    # 数据源配置
    datasource:
      names: ds-master-0
      ds-master-0:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://10.10.111.129:3306/sys_account?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: profit
        password: haoshikisses
#        url: jdbc:mysql://127.0.0.1:3306/sys_account?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#        username: root
#        password: 123456
        #        connection-properties: config.decrypt=true;config.decrypt.key=${frame.datasource.decrypt-key}

        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
        time-between-log-stats-millis: 60000
        filters: stat,wall,config

    # 属性
    props:
      # 打印sql
      sql.show: true
      check:
        table:
          metadata:
            # 是否在启动时检查分表元数据一致性
            enabled: false
    # 分库分表策略
    sharding:
      # 默认数据源
      default-data-source-name: ds-0
      # 读写分离
      master-slave-rules:
        ds-0:
          master-data-source-name: ds-master-0
          slave-data-source-names: ds-master-0, ds-master-0
        ds-1:
          master-data-source-name: ds-master-0
          slave-data-source-names: ds-master-0, ds-master-0
#      # 默认ID生成策略
#      default-key-generator:
#        type: SNOWFLAKE
#        column: id

      # 默认分库策略
      default-database-strategy:
        none:
          all: "随便，无须配置，只是为了匹配规则"

      # 默认分表策略
      default-table-strategy:
        standard:
          sharding-column: count_date
          precise-algorithm-class-name: com.frame.boot.sharding.DateMonthShardingAlgorithm
          range-algorithm-class-name: com.frame.boot.sharding.DateMonthShardingAlgorithm
      tables:
        test:
          actual-data-nodes: ds-$->{0..1}.TEST_$->{1..2}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: ds-$->{id % 2}.TEST_$->{id % 2}
          key-generator:
            column: id
            type: SNOWFLAKE
# mybatis-plus
mybatis-plus:
  type-aliases-package: com.**.entity.**
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    # 字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    # 驼峰下划线转换
    db-column-underline: true
    # 刷新mapper 调试神器
    refresh-mapper: true
    # 数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false