server:
  port: 12100

info:
  name: @project.name@
  version: @project.version@
  description: @project.description@

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always