info:
  name: @project.artifactId@
  version: @project.version@
  description: @project.description@

server:
  port: 1111

# eureka config
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 10

# spring config
spring:
  application:
    name: @project.artifactId@
  jmx:
    default-domain: @project.artifactId@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true