server:
  port: 20001

info:
  name: @project.artifactId@
  version: @project.version@
  description: @project.description@

security:
  oauth2:
    sso:
      login-path: http://127.0.0.1:9999/login/login.html
      index-path: http://127.0.0.1:9999/boss/index.html

    frame:
      client:
        client-id: ${info.name}
        client-secret: 123456
        scope: all
        access-token-uri: http://127.0.0.1:20002/oauth/token
        user-authorization-uri: http://127.0.0.1:20002/oauth/authorize
        registered-redirect-uri: http://127.0.0.1:9999/boss/index.html
      resource:
        user-info-uri: http://127.0.0.1:20002/pub/oauth/getInfo
    baidu:
      client:
        client-id: r17oBL2hbSzq4GrcRmbqi81s
        client-secret: zkqYxPfwmjKxteVNUSRrW5sZ8EvvNDIk
        scope: basic
        access-token-uri: https://openapi.baidu.com/oauth/2.0/token
        user-authorization-uri: https://openapi.baidu.com/oauth/2.0/authorize
        registered-redirect-uri: http://127.0.0.1:20001/login/baidu
      resource:
        user-info-uri: https://openapi.baidu.com/rest/2.0/passport/users/getInfo
    qq:
      client:
        client-id: 56f645382884bfd6fea8
        client-secret: e35cb6d4bde3a4d3fa56b8a323996cabda7af214
        scope: get_user_info,list_album,upload_pic,do_like
        access-token-uri: https://graph.qq.com/oauth2.0/token
        user-authorization-uri: https://graph.qq.com/oauth2.0/authorize
        registered-redirect-uri: http://127.0.0.1:20001/login/qq
      resource:
        user-info-uri: https://graph.qq.com/user/get_user_info
    weibo:
      client:
        client-id: 2442386264
        client-secret: e69a315a3f668576f783799d7a553268
        scope: all
        access-token-uri: https://api.weibo.com/oauth2/access_token
        user-authorization-uri: https://api.weibo.com/oauth2/authorize
        registered-redirect-uri: http://127.0.0.1:20001/login/weibo
      resource:
        user-info-uri: https://api.weibo.com/oauth2/get_token_info
    github:
      client:
        client-id: 56f645382884bfd6fea8
        client-secret: e35cb6d4bde3a4d3fa56b8a323996cabda7af214
        access-token-uri: https://github.com/login/oauth/access_token
        user-authorization-uri: https://github.com/login/oauth/authorize
        registered-redirect-uri: http://127.0.0.1:20001/login/github
        client-authentication-scheme: form
      resource:
        user-info-uri: https://api.github.com/user