server:
  port: 10001

info:
  name: @project.name@
  version: @project.version@
  description: @project.description@

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# spring config
spring:
  profiles:
    include: ds
  application:
    name: @project.artifactId@
  jmx:
    default-domain: @project.artifactId@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true